import { jetBrains, inter } from "~/lib/fonts";
import type { Metadata } from "next";
import "~/styles/globals.css";
import { Navigation } from "~/components/shared";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetBrains.variable} ${inter.className} antialiased w-full h-full bg-background scroll-smooth`}
      >
        <Navigation />
        <main className="min-h-screen flex flex-col items-center justify-center px-8 py-36">
          {children}
        </main>
      </body>
    </html>
  );
}
